http: 
  listener:    
    host: "localhost"
    port: "8082"
    path: "/FastGocall/{serviceType}"

db:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Venkat001@"
    database: "database" 